[package]
name = "kubernetes_context_gen"
version = "0.1.0"
authors = ["Noah <turing.thesis@gmail.com>"]

[dependencies]
colored = "1.6.1"
failure = "0.1.2"
rust-s3 = "0.9.2"
openssl = "0.10.11"
reqwest = "0.8.7"